/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A file that will be written to the Machine. One of RawValue or SecretName must be set.
*/
export class ApiFile {
    /**
    * GuestPath is the path on the machine where the file will be written and must be an absolute path. For example: /full/path/to/file.json
    */
    'guestPath'?: string;
    /**
    * The base64 encoded string of the file contents.
    */
    'rawValue'?: string;
    /**
    * The name of the secret that contains the base64 encoded file contents.
    */
    'secretName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "guestPath",
            "baseName": "guest_path",
            "type": "string"
        },
        {
            "name": "rawValue",
            "baseName": "raw_value",
            "type": "string"
        },
        {
            "name": "secretName",
            "baseName": "secret_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApiFile.attributeTypeMap;
    }
}

