/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiHTTPResponseOptions } from './apiHTTPResponseOptions';

export class ApiHTTPOptions {
    'compress'?: boolean;
    'h2Backend'?: boolean;
    'response'?: ApiHTTPResponseOptions;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "compress",
            "baseName": "compress",
            "type": "boolean"
        },
        {
            "name": "h2Backend",
            "baseName": "h2_backend",
            "type": "boolean"
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "ApiHTTPResponseOptions"
        }    ];

    static getAttributeTypeMap() {
        return ApiHTTPOptions.attributeTypeMap;
    }
}

