/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiMachineCheck } from './apiMachineCheck';
import { ApiMachinePort } from './apiMachinePort';
import { ApiMachineServiceConcurrency } from './apiMachineServiceConcurrency';

export class ApiMachineService {
    'autostart'?: boolean;
    'autostop'?: boolean;
    'checks'?: Array<ApiMachineCheck>;
    'concurrency'?: ApiMachineServiceConcurrency;
    'forceInstanceDescription'?: string;
    'forceInstanceKey'?: string;
    'internalPort'?: number;
    'minMachinesRunning'?: number;
    'ports'?: Array<ApiMachinePort>;
    'protocol'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "autostart",
            "baseName": "autostart",
            "type": "boolean"
        },
        {
            "name": "autostop",
            "baseName": "autostop",
            "type": "boolean"
        },
        {
            "name": "checks",
            "baseName": "checks",
            "type": "Array<ApiMachineCheck>"
        },
        {
            "name": "concurrency",
            "baseName": "concurrency",
            "type": "ApiMachineServiceConcurrency"
        },
        {
            "name": "forceInstanceDescription",
            "baseName": "force_instance_description",
            "type": "string"
        },
        {
            "name": "forceInstanceKey",
            "baseName": "force_instance_key",
            "type": "string"
        },
        {
            "name": "internalPort",
            "baseName": "internal_port",
            "type": "number"
        },
        {
            "name": "minMachinesRunning",
            "baseName": "min_machines_running",
            "type": "number"
        },
        {
            "name": "ports",
            "baseName": "ports",
            "type": "Array<ApiMachinePort>"
        },
        {
            "name": "protocol",
            "baseName": "protocol",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApiMachineService.attributeTypeMap;
    }
}

