/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ApiMachineGuest {
    'cpuKind'?: string;
    'cpus'?: number;
    'gpuKind'?: string;
    'hostDedicationId'?: string;
    'kernelArgs'?: Array<string>;
    'memoryMb'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cpuKind",
            "baseName": "cpu_kind",
            "type": "string"
        },
        {
            "name": "cpus",
            "baseName": "cpus",
            "type": "number"
        },
        {
            "name": "gpuKind",
            "baseName": "gpu_kind",
            "type": "string"
        },
        {
            "name": "hostDedicationId",
            "baseName": "host_dedication_id",
            "type": "string"
        },
        {
            "name": "kernelArgs",
            "baseName": "kernel_args",
            "type": "Array<string>"
        },
        {
            "name": "memoryMb",
            "baseName": "memory_mb",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ApiMachineGuest.attributeTypeMap;
    }
}

