/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiMachineHTTPHeader } from './apiMachineHTTPHeader';

/**
* An optional object that defines one or more named checks. The key for each check is the check name.
*/
export class ApiMachineCheck {
    /**
    * The time to wait after a VM starts before checking its health
    */
    'gracePeriod'?: string;
    'headers'?: Array<ApiMachineHTTPHeader>;
    /**
    * The time between connectivity checks
    */
    'interval'?: string;
    /**
    * For http checks, the HTTP method to use to when making the request
    */
    'method'?: string;
    /**
    * For http checks, the path to send the request to
    */
    'path'?: string;
    /**
    * The port to connect to, often the same as internal_port
    */
    'port'?: number;
    /**
    * For http checks, whether to use http or https
    */
    'protocol'?: string;
    /**
    * The maximum time a connection can take before being reported as failing its health check
    */
    'timeout'?: string;
    /**
    * If the protocol is https, the hostname to use for TLS certificate validation
    */
    'tlsServerName'?: string;
    /**
    * For http checks with https protocol, whether or not to verify the TLS certificate
    */
    'tlsSkipVerify'?: boolean;
    /**
    * tcp or http
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "gracePeriod",
            "baseName": "grace_period",
            "type": "string"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "Array<ApiMachineHTTPHeader>"
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "string"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number"
        },
        {
            "name": "protocol",
            "baseName": "protocol",
            "type": "string"
        },
        {
            "name": "timeout",
            "baseName": "timeout",
            "type": "string"
        },
        {
            "name": "tlsServerName",
            "baseName": "tls_server_name",
            "type": "string"
        },
        {
            "name": "tlsSkipVerify",
            "baseName": "tls_skip_verify",
            "type": "boolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApiMachineCheck.attributeTypeMap;
    }
}

