/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiDNSConfig } from './apiDNSConfig';
import { ApiFile } from './apiFile';
import { ApiMachineCheck } from './apiMachineCheck';
import { ApiMachineGuest } from './apiMachineGuest';
import { ApiMachineInit } from './apiMachineInit';
import { ApiMachineMetrics } from './apiMachineMetrics';
import { ApiMachineMount } from './apiMachineMount';
import { ApiMachineProcess } from './apiMachineProcess';
import { ApiMachineRestart } from './apiMachineRestart';
import { ApiMachineService } from './apiMachineService';
import { ApiStatic } from './apiStatic';
import { ApiStopConfig } from './apiStopConfig';

export class ApiMachineConfig {
    /**
    * Optional boolean telling the Machine to destroy itself once it’s complete (default false)
    */
    'autoDestroy'?: boolean;
    'checks'?: { [key: string]: ApiMachineCheck; };
    /**
    * Deprecated: use Service.Autostart instead
    */
    'disableMachineAutostart'?: boolean;
    'dns'?: ApiDNSConfig;
    /**
    * An object filled with key/value pairs to be set as environment variables
    */
    'env'?: { [key: string]: string; };
    'files'?: Array<ApiFile>;
    'guest'?: ApiMachineGuest;
    /**
    * The docker image to run
    */
    'image'?: string;
    'init'?: ApiMachineInit;
    'metadata'?: { [key: string]: string; };
    'metrics'?: ApiMachineMetrics;
    'mounts'?: Array<ApiMachineMount>;
    'processes'?: Array<ApiMachineProcess>;
    'restart'?: ApiMachineRestart;
    'schedule'?: string;
    'services'?: Array<ApiMachineService>;
    /**
    * Deprecated: use Guest instead
    */
    'size'?: string;
    /**
    * Standbys enable a machine to be a standby for another. In the event of a hardware failure, the standby machine will be started.
    */
    'standbys'?: Array<string>;
    'statics'?: Array<ApiStatic>;
    'stopConfig'?: ApiStopConfig;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "autoDestroy",
            "baseName": "auto_destroy",
            "type": "boolean"
        },
        {
            "name": "checks",
            "baseName": "checks",
            "type": "{ [key: string]: ApiMachineCheck; }"
        },
        {
            "name": "disableMachineAutostart",
            "baseName": "disable_machine_autostart",
            "type": "boolean"
        },
        {
            "name": "dns",
            "baseName": "dns",
            "type": "ApiDNSConfig"
        },
        {
            "name": "env",
            "baseName": "env",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<ApiFile>"
        },
        {
            "name": "guest",
            "baseName": "guest",
            "type": "ApiMachineGuest"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string"
        },
        {
            "name": "init",
            "baseName": "init",
            "type": "ApiMachineInit"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "metrics",
            "baseName": "metrics",
            "type": "ApiMachineMetrics"
        },
        {
            "name": "mounts",
            "baseName": "mounts",
            "type": "Array<ApiMachineMount>"
        },
        {
            "name": "processes",
            "baseName": "processes",
            "type": "Array<ApiMachineProcess>"
        },
        {
            "name": "restart",
            "baseName": "restart",
            "type": "ApiMachineRestart"
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "string"
        },
        {
            "name": "services",
            "baseName": "services",
            "type": "Array<ApiMachineService>"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "string"
        },
        {
            "name": "standbys",
            "baseName": "standbys",
            "type": "Array<string>"
        },
        {
            "name": "statics",
            "baseName": "statics",
            "type": "Array<ApiStatic>"
        },
        {
            "name": "stopConfig",
            "baseName": "stop_config",
            "type": "ApiStopConfig"
        }    ];

    static getAttributeTypeMap() {
        return ApiMachineConfig.attributeTypeMap;
    }
}

