/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ApiMachineMount {
    'addSizeGb'?: number;
    'encrypted'?: boolean;
    'extendThresholdPercent'?: number;
    'name'?: string;
    'path'?: string;
    'sizeGb'?: number;
    'sizeGbLimit'?: number;
    'volume'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addSizeGb",
            "baseName": "add_size_gb",
            "type": "number"
        },
        {
            "name": "encrypted",
            "baseName": "encrypted",
            "type": "boolean"
        },
        {
            "name": "extendThresholdPercent",
            "baseName": "extend_threshold_percent",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "sizeGb",
            "baseName": "size_gb",
            "type": "number"
        },
        {
            "name": "sizeGbLimit",
            "baseName": "size_gb_limit",
            "type": "number"
        },
        {
            "name": "volume",
            "baseName": "volume",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApiMachineMount.attributeTypeMap;
    }
}

