/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ApiMachineInit {
    'cmd'?: Array<string>;
    'entrypoint'?: Array<string>;
    'exec'?: Array<string>;
    'kernelArgs'?: Array<string>;
    'swapSizeMb'?: number;
    'tty'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cmd",
            "baseName": "cmd",
            "type": "Array<string>"
        },
        {
            "name": "entrypoint",
            "baseName": "entrypoint",
            "type": "Array<string>"
        },
        {
            "name": "exec",
            "baseName": "exec",
            "type": "Array<string>"
        },
        {
            "name": "kernelArgs",
            "baseName": "kernel_args",
            "type": "Array<string>"
        },
        {
            "name": "swapSizeMb",
            "baseName": "swap_size_mb",
            "type": "number"
        },
        {
            "name": "tty",
            "baseName": "tty",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ApiMachineInit.attributeTypeMap;
    }
}

