/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiHTTPOptions } from './apiHTTPOptions';
import { ApiProxyProtoOptions } from './apiProxyProtoOptions';
import { ApiTLSOptions } from './apiTLSOptions';

export class ApiMachinePort {
    'endPort'?: number;
    'forceHttps'?: boolean;
    'handlers'?: Array<string>;
    'httpOptions'?: ApiHTTPOptions;
    'port'?: number;
    'proxyProtoOptions'?: ApiProxyProtoOptions;
    'startPort'?: number;
    'tlsOptions'?: ApiTLSOptions;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "endPort",
            "baseName": "end_port",
            "type": "number"
        },
        {
            "name": "forceHttps",
            "baseName": "force_https",
            "type": "boolean"
        },
        {
            "name": "handlers",
            "baseName": "handlers",
            "type": "Array<string>"
        },
        {
            "name": "httpOptions",
            "baseName": "http_options",
            "type": "ApiHTTPOptions"
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number"
        },
        {
            "name": "proxyProtoOptions",
            "baseName": "proxy_proto_options",
            "type": "ApiProxyProtoOptions"
        },
        {
            "name": "startPort",
            "baseName": "start_port",
            "type": "number"
        },
        {
            "name": "tlsOptions",
            "baseName": "tls_options",
            "type": "ApiTLSOptions"
        }    ];

    static getAttributeTypeMap() {
        return ApiMachinePort.attributeTypeMap;
    }
}

