/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ApiMachineProcess {
    'cmd'?: Array<string>;
    'entrypoint'?: Array<string>;
    'env'?: { [key: string]: string; };
    'exec'?: Array<string>;
    'user'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cmd",
            "baseName": "cmd",
            "type": "Array<string>"
        },
        {
            "name": "entrypoint",
            "baseName": "entrypoint",
            "type": "Array<string>"
        },
        {
            "name": "env",
            "baseName": "env",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "exec",
            "baseName": "exec",
            "type": "Array<string>"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApiMachineProcess.attributeTypeMap;
    }
}

