/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ApiTLSOptions {
    'alpn'?: Array<string>;
    'defaultSelfSigned'?: boolean;
    'versions'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "alpn",
            "baseName": "alpn",
            "type": "Array<string>"
        },
        {
            "name": "defaultSelfSigned",
            "baseName": "default_self_signed",
            "type": "boolean"
        },
        {
            "name": "versions",
            "baseName": "versions",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ApiTLSOptions.attributeTypeMap;
    }
}

