/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiMachineGuest } from './apiMachineGuest';

export class CreateVolumeRequest {
    'compute'?: ApiMachineGuest;
    'encrypted'?: boolean;
    'fstype'?: string;
    'machinesOnly'?: boolean;
    'name'?: string;
    'region'?: string;
    'requireUniqueZone'?: boolean;
    'sizeGb'?: number;
    /**
    * restore from snapshot
    */
    'snapshotId'?: string;
    'snapshotRetention'?: number;
    /**
    * fork from remote volume
    */
    'sourceVolumeId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "compute",
            "baseName": "compute",
            "type": "ApiMachineGuest"
        },
        {
            "name": "encrypted",
            "baseName": "encrypted",
            "type": "boolean"
        },
        {
            "name": "fstype",
            "baseName": "fstype",
            "type": "string"
        },
        {
            "name": "machinesOnly",
            "baseName": "machines_only",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "requireUniqueZone",
            "baseName": "require_unique_zone",
            "type": "boolean"
        },
        {
            "name": "sizeGb",
            "baseName": "size_gb",
            "type": "number"
        },
        {
            "name": "snapshotId",
            "baseName": "snapshot_id",
            "type": "string"
        },
        {
            "name": "snapshotRetention",
            "baseName": "snapshot_retention",
            "type": "number"
        },
        {
            "name": "sourceVolumeId",
            "baseName": "source_volume_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateVolumeRequest.attributeTypeMap;
    }
}

