/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiMachineConfig } from './apiMachineConfig';

export class CreateMachineRequest {
    'config'?: ApiMachineConfig;
    'leaseTtl'?: number;
    'lsvd'?: boolean;
    /**
    * Unique name for this Machine. If omitted, one is generated for you
    */
    'name'?: string;
    /**
    * The target region. Omitting this param launches in the same region as your WireGuard peer connection (somewhere near you).
    */
    'region'?: string;
    'skipLaunch'?: boolean;
    'skipServiceRegistration'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "config",
            "baseName": "config",
            "type": "ApiMachineConfig"
        },
        {
            "name": "leaseTtl",
            "baseName": "lease_ttl",
            "type": "number"
        },
        {
            "name": "lsvd",
            "baseName": "lsvd",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "skipLaunch",
            "baseName": "skip_launch",
            "type": "boolean"
        },
        {
            "name": "skipServiceRegistration",
            "baseName": "skip_service_registration",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CreateMachineRequest.attributeTypeMap;
    }
}

