/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateAppRequest {
    'appName'?: string;
    'appRoleId'?: string;
    'network'?: string;
    'orgSlug'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "appName",
            "baseName": "app_name",
            "type": "string"
        },
        {
            "name": "appRoleId",
            "baseName": "app_role_id",
            "type": "string"
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "string"
        },
        {
            "name": "orgSlug",
            "baseName": "org_slug",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateAppRequest.attributeTypeMap;
    }
}

