/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Volume } from './volume';

export class ExtendVolumeResponse {
    'needsRestart'?: boolean;
    'volume'?: Volume;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "needsRestart",
            "baseName": "needs_restart",
            "type": "boolean"
        },
        {
            "name": "volume",
            "baseName": "volume",
            "type": "Volume"
        }    ];

    static getAttributeTypeMap() {
        return ExtendVolumeResponse.attributeTypeMap;
    }
}

