/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Lease {
    /**
    * Description or reason for the Lease.
    */
    'description'?: string;
    /**
    * ExpiresAt is the unix timestamp in UTC to denote when the Lease will no longer be valid.
    */
    'expiresAt'?: number;
    /**
    * Nonce is the unique ID autogenerated and associated with the Lease.
    */
    'nonce'?: string;
    /**
    * Owner is the user identifier which acquired the Lease.
    */
    'owner'?: string;
    /**
    * Machine version
    */
    'version'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "number"
        },
        {
            "name": "nonce",
            "baseName": "nonce",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Lease.attributeTypeMap;
    }
}

