/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiMachineConfig } from './apiMachineConfig';
import { CheckStatus } from './checkStatus';
import { ImageRef } from './imageRef';
import { MachineEvent } from './machineEvent';

export class Machine {
    'checks'?: Array<CheckStatus>;
    'config'?: ApiMachineConfig;
    'createdAt'?: string;
    'events'?: Array<MachineEvent>;
    'id'?: string;
    'imageRef'?: ImageRef;
    /**
    * InstanceID is unique for each version of the machine
    */
    'instanceId'?: string;
    'name'?: string;
    /**
    * Nonce is only every returned on machine creation if a lease_duration was provided.
    */
    'nonce'?: string;
    /**
    * PrivateIP is the internal 6PN address of the machine.
    */
    'privateIp'?: string;
    'region'?: string;
    'state'?: string;
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "checks",
            "baseName": "checks",
            "type": "Array<CheckStatus>"
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "ApiMachineConfig"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<MachineEvent>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "imageRef",
            "baseName": "image_ref",
            "type": "ImageRef"
        },
        {
            "name": "instanceId",
            "baseName": "instance_id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "nonce",
            "baseName": "nonce",
            "type": "string"
        },
        {
            "name": "privateIp",
            "baseName": "private_ip",
            "type": "string"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Machine.attributeTypeMap;
    }
}

