/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListenSocket } from './listenSocket';

export class ProcessStat {
    'command'?: string;
    'cpu'?: number;
    'directory'?: string;
    'listenSockets'?: Array<ListenSocket>;
    'pid'?: number;
    'rss'?: number;
    'rtime'?: number;
    'stime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "command",
            "baseName": "command",
            "type": "string"
        },
        {
            "name": "cpu",
            "baseName": "cpu",
            "type": "number"
        },
        {
            "name": "directory",
            "baseName": "directory",
            "type": "string"
        },
        {
            "name": "listenSockets",
            "baseName": "listen_sockets",
            "type": "Array<ListenSocket>"
        },
        {
            "name": "pid",
            "baseName": "pid",
            "type": "number"
        },
        {
            "name": "rss",
            "baseName": "rss",
            "type": "number"
        },
        {
            "name": "rtime",
            "baseName": "rtime",
            "type": "number"
        },
        {
            "name": "stime",
            "baseName": "stime",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ProcessStat.attributeTypeMap;
    }
}

