/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SignalRequest {
    'signal'?: SignalRequest.SignalEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "signal",
            "baseName": "signal",
            "type": "SignalRequest.SignalEnum"
        }    ];

    static getAttributeTypeMap() {
        return SignalRequest.attributeTypeMap;
    }
}

export namespace SignalRequest {
    export enum SignalEnum {
        Sigabrt = <any> 'SIGABRT',
        Sigalrm = <any> 'SIGALRM',
        Sigfpe = <any> 'SIGFPE',
        Sighup = <any> 'SIGHUP',
        Sigill = <any> 'SIGILL',
        Sigint = <any> 'SIGINT',
        Sigkill = <any> 'SIGKILL',
        Sigpipe = <any> 'SIGPIPE',
        Sigquit = <any> 'SIGQUIT',
        Sigsegv = <any> 'SIGSEGV',
        Sigterm = <any> 'SIGTERM',
        Sigtrap = <any> 'SIGTRAP',
        Sigusr1 = <any> 'SIGUSR1'
    }
}
