/**
 * Fly Machines API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Volume {
    'attachedAllocId'?: string;
    'attachedMachineId'?: string;
    'blockSize'?: number;
    'blocks'?: number;
    'blocksAvail'?: number;
    'blocksFree'?: number;
    'createdAt'?: string;
    'encrypted'?: boolean;
    'fstype'?: string;
    'id'?: string;
    'name'?: string;
    'region'?: string;
    'sizeGb'?: number;
    'snapshotRetention'?: number;
    'state'?: string;
    'zone'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "attachedAllocId",
            "baseName": "attached_alloc_id",
            "type": "string"
        },
        {
            "name": "attachedMachineId",
            "baseName": "attached_machine_id",
            "type": "string"
        },
        {
            "name": "blockSize",
            "baseName": "block_size",
            "type": "number"
        },
        {
            "name": "blocks",
            "baseName": "blocks",
            "type": "number"
        },
        {
            "name": "blocksAvail",
            "baseName": "blocks_avail",
            "type": "number"
        },
        {
            "name": "blocksFree",
            "baseName": "blocks_free",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "encrypted",
            "baseName": "encrypted",
            "type": "boolean"
        },
        {
            "name": "fstype",
            "baseName": "fstype",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "sizeGb",
            "baseName": "size_gb",
            "type": "number"
        },
        {
            "name": "snapshotRetention",
            "baseName": "snapshot_retention",
            "type": "number"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "zone",
            "baseName": "zone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Volume.attributeTypeMap;
    }
}

